import type { ActivityKind, CourseId } from './academyTypes'
import type { Language } from './types'

const activityKinds: Record<Language, Record<ActivityKind, string>> = {
  es: {
    lesson: 'Concepto',
    guided: 'Práctica guiada',
    puzzle: 'Puzle',
    exam: 'Examen',
  },
  en: {
    lesson: 'Concept',
    guided: 'Guided practice',
    puzzle: 'Puzzle',
    exam: 'Exam',
  },
}

export function getActivityKindLabel(kind: ActivityKind, language: Language): string {
  return activityKinds[language][kind]
}

export function getCourseLabel(course: CourseId, language: Language): string {
  if (language === 'es') return course === 'classic' ? 'Ruta clásica' : 'Ruta cuántica'
  return course === 'classic' ? 'Classic route' : 'Quantum route'
}

export function academyCopy(language: Language) {
  const es = language === 'es'
  return es
    ? {
        product: 'Academia Estratégica Cuántica',
        eyebrow: 'Aprende a decidir, no a memorizar',
        headline: 'Dos tableros. Una forma más profunda de pensar.',
        intro: 'Avanza por habilidades, practica sin presión y vuelve justo cuando tu memoria necesita refuerzo.',
        back: 'Inicio',
        settings: 'Ajustes',
        routeProgress: 'Progreso de ruta',
        mastery: 'dominio',
        completed: 'completadas',
        streak: 'racha',
        days: 'días',
        next: 'Siguiente paso',
        start: 'Empezar',
        continue: 'Continuar',
        review: 'Repasar ahora',
        routeComplete: 'Ruta fundamental completada',
        routeCompleteDetail: 'Puedes seguir repasando para consolidar cada habilidad.',
        dueReviews: 'repasos pendientes',
        skillMap: 'Mapa de habilidades',
        skillMapIntro: 'Puedes inspeccionar toda la ruta. Completa cada módulo y demuestra dominio para abrir el siguiente.',
        diagnostic: 'Diagnóstico inicial',
        diagnosticDetail: 'Cuatro preguntas, sin penalización. El resultado nunca fijará un dominio superior a 60.',
        takeDiagnostic: 'Hacer diagnóstico',
        retakeDiagnostic: 'Repetir diagnóstico',
        daily: 'Laboratorio diario',
        dailyDetail: 'La misma semilla para toda la comunidad.',
        dailyAction: 'Abrir reto',
        sprint: 'Puzzle Sprint',
        sprintDetail: 'Encadena decisiones correctas contra el reloj.',
        errorBook: 'Cuaderno de errores',
        errorBookEmpty: 'Todavía no hay errores que revisar.',
        errorBookAction: 'Revisar último error',
        reviewQueue: 'Cola de repaso',
        reviewQueueEmpty: 'Estás al día. El próximo repaso aparecerá aquí.',
        locked: 'Necesita dominio 70 y dos resoluciones independientes del módulo anterior.',
        open: 'Abrir actividad',
        minutes: 'min',
        diagnosticTitle: 'Calibra tu punto de partida',
        diagnosticIntro: 'Responde las cuatro preguntas sin pistas. Podrás recorrer igualmente todo el contenido disponible.',
        diagnosticQuestion: 'Pregunta',
        finishDiagnostic: 'Calcular nivel inicial',
        cancel: 'Ahora no',
        answered: 'respondidas',
        diagnosticResult: 'Diagnóstico guardado. Las lecciones comprobarán después ese nivel.',
        loading: 'Recuperando tu progreso local…',
        independent: 'resoluciones independientes',
        studyModes: 'Entrenamiento',
        sprint3: '3 min',
        sprint5: '5 min',
        sprint10: '10 min',
      }
    : {
        product: 'Quantum Strategy Academy',
        eyebrow: 'Learn to decide, not to memorise',
        headline: 'Two boards. One deeper way to think.',
        intro: 'Advance by skill, practise without pressure, and return when your memory needs reinforcement.',
        back: 'Home',
        settings: 'Settings',
        routeProgress: 'Route progress',
        mastery: 'mastery',
        completed: 'completed',
        streak: 'streak',
        days: 'days',
        next: 'Next step',
        start: 'Start',
        continue: 'Continue',
        review: 'Review now',
        routeComplete: 'Foundation route completed',
        routeCompleteDetail: 'Keep reviewing to consolidate every skill.',
        dueReviews: 'reviews due',
        skillMap: 'Skill map',
        skillMapIntro: 'Inspect the whole route. Complete each module and prove mastery to open the next one.',
        diagnostic: 'Initial assessment',
        diagnosticDetail: 'Four questions, no penalty. The result never sets mastery above 60.',
        takeDiagnostic: 'Take assessment',
        retakeDiagnostic: 'Retake assessment',
        daily: 'Daily laboratory',
        dailyDetail: 'The same seed for the whole community.',
        dailyAction: 'Open challenge',
        sprint: 'Puzzle Sprint',
        sprintDetail: 'Chain correct decisions against the clock.',
        errorBook: 'Error notebook',
        errorBookEmpty: 'There are no mistakes to review yet.',
        errorBookAction: 'Review latest mistake',
        reviewQueue: 'Review queue',
        reviewQueueEmpty: 'You are up to date. Your next review will appear here.',
        locked: 'Requires 70 mastery and two independent solves in the previous module.',
        open: 'Open activity',
        minutes: 'min',
        diagnosticTitle: 'Calibrate your starting point',
        diagnosticIntro: 'Answer four questions without hints. You can still browse all currently available content.',
        diagnosticQuestion: 'Question',
        finishDiagnostic: 'Calculate starting level',
        cancel: 'Not now',
        answered: 'answered',
        diagnosticResult: 'Assessment saved. Lessons will verify that level later.',
        loading: 'Restoring your local progress…',
        independent: 'independent solves',
        studyModes: 'Training',
        sprint3: '3 min',
        sprint5: '5 min',
        sprint10: '10 min',
      }
}

export function lessonCopy(language: Language) {
  const es = language === 'es'
  return es
    ? {
        back: 'Volver al mapa',
        objective: 'Objetivo',
        activity: 'Actividad',
        hint: 'Pedir una pista',
        hints: 'Pistas',
        noHintsExam: 'El examen no admite pistas.',
        choose: 'Elige una respuesta',
        confirm: 'Confirmar respuesta',
        correct: 'Decisión correcta',
        incorrect: 'Todavía no',
        score: 'Puntuación del intento',
        explanation: 'Por qué',
        retry: 'Intentar de nuevo',
        next: 'Siguiente actividad',
        map: 'Volver al mapa',
        reviewMode: 'Este intento cuenta como repaso espaciado.',
        independent: 'Sin pistas: resolución independiente',
        assisted: 'Resolución asistida',
        answerRequired: 'Selecciona una respuesta antes de confirmar.',
        progress: 'Progreso del módulo',
        laboratory: '¿Qué habría pasado si…?',
        laboratoryDetail: 'Compara las demás decisiones sin alterar tu intento guardado.',
        closeLab: 'Cerrar comparación',
        outcomeCorrect: 'Conserva el principio y mejora la posición.',
        outcomeWrong: 'Introduce una concesión o contradice la regla estudiada.',
      }
    : {
        back: 'Back to map',
        objective: 'Objective',
        activity: 'Activity',
        hint: 'Request a hint',
        hints: 'Hints',
        noHintsExam: 'Exams do not allow hints.',
        choose: 'Choose an answer',
        confirm: 'Confirm answer',
        correct: 'Correct decision',
        incorrect: 'Not yet',
        score: 'Attempt score',
        explanation: 'Why',
        retry: 'Try again',
        next: 'Next activity',
        map: 'Back to map',
        reviewMode: 'This attempt counts as spaced review.',
        independent: 'No hints: independent solve',
        assisted: 'Assisted solve',
        answerRequired: 'Select an answer before confirming.',
        progress: 'Module progress',
        laboratory: 'What would have happened if…?',
        laboratoryDetail: 'Compare the other decisions without changing your saved attempt.',
        closeLab: 'Close comparison',
        outcomeCorrect: 'Preserves the principle and improves the position.',
        outcomeWrong: 'Makes a concession or contradicts the rule being studied.',
      }
}

export function sprintCopy(language: Language) {
  return language === 'es'
    ? {
        title: 'Puzzle Sprint',
        back: 'Terminar y volver',
        privateAttempt: 'Sesión local · el progreso se guarda, pero no entra en clasificaciones.',
        score: 'puntos',
        correct: 'correctas',
        streak: 'mejor cadena',
        question: 'Decisión',
        choose: 'Elige y continúa',
        finishTitle: 'Sprint completado',
        finishDetail: 'Las habilidades practicadas ya están en tu cola de repaso.',
        again: 'Repetir sprint',
        map: 'Volver a la Academia',
        time: 'Tiempo restante',
      }
    : {
        title: 'Puzzle Sprint',
        back: 'Finish and return',
        privateAttempt: 'Local session · progress is saved but does not enter leaderboards.',
        score: 'points',
        correct: 'correct',
        streak: 'best chain',
        question: 'Decision',
        choose: 'Choose and continue',
        finishTitle: 'Sprint complete',
        finishDetail: 'The skills you practised are now part of your review queue.',
        again: 'Repeat sprint',
        map: 'Back to Academy',
        time: 'Time remaining',
      }
}
